# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 828c3ee53b695869e8b810abfeefa2201dc38b2c7324e1b6065aa3bda18e97998bb976ed7d19533f4fd0e0bd798a57b7cdcd9606555fe8e1662436d9ebb33a34

test:
  secret_key_base: 238092158708732f86fff77f493f6b770fbe17d53a53e0310d132ef254f2c132266b058c0da91d1315684a840b5e7bdf465b908c07e61d1c6f0f79446cfdbab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
